local colors = {
  Normal = { fg = '#C7CBE1', bg = '#151828' },
  Ignore = { link = 'Normal' },
  NvimSpacing = { link = 'Normal' },
  TelescopeNormal = { link = 'Normal' },
  WhichKeyIconGrey = { link = 'Normal' },
  WinSeparator = { link = 'Normal' },
  Added = { fg = '#B1F6BF' },
  GitSignsAdd = { link = 'Added' },
  ['@diff.plus'] = { link = 'Added' },
  Changed = { fg = '#FFDD99' },
  GitSignsChange = { link = 'Changed' },
  ['@diff.delta'] = { link = 'Changed' },
  ColorColumn = { bg = '#20253C' },
  Comment = { fg = '#A5ACCF' },
  DiagnosticUnnecessary = { link = 'Comment' },
  TelescopeResultsComment = { link = 'Comment' },
  WhichKeySeparator = { link = 'Comment' },
  WhichKeyValue = { link = 'Comment' },
  ['@comment'] = { link = 'Comment' },
  Conceal = { fg = '#151828' },
  Constant = { fg = '#B1F6E1' },
  Boolean = { link = 'Constant' },
  Character = { link = 'Constant' },
  Number = { link = 'Constant' },
  TelescopePreviewBlock = { link = 'Constant' },
  TelescopePreviewCharDev = { link = 'Constant' },
  TelescopePreviewGroup = { link = 'Constant' },
  TelescopePreviewPipe = { link = 'Constant' },
  TelescopePreviewRead = { link = 'Constant' },
  TelescopePreviewUser = { link = 'Constant' },
  TelescopeResultsConstant = { link = 'Constant' },
  WhichKeyIconPurple = { link = 'Constant' },
  ['@constant'] = { link = 'Constant' },
  CurSearch = { fg = '#151828', bg = '#FFDD99' },
  IncSearch = { link = 'CurSearch' },
  Cursor = { fg = 'bg', bg = 'fg' },
  CursorIM = { link = 'Cursor' },
  CursorColumn = { bg = '#20253C' },
  CursorLine = { bg = '#20253C' },
  CursorLineNr = { fg = '#C7CBE1', bold = true },
  Delimiter = { fg = '#A5ACCF' },
  NvimArrow = { link = 'Delimiter' },
  NvimColon = { link = 'Delimiter' },
  NvimComma = { link = 'Delimiter' },
  NvimParenthesis = { link = 'Delimiter' },
  ['@punctuation'] = { link = 'Delimiter' },
  DiagnosticDeprecated = { sp = '#FF9999', strikethrough = true },
  ['@lsp.mod.deprecated'] = { link = 'DiagnosticDeprecated' },
  DiagnosticError = { fg = '#FF9999' },
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticVirtualLinesError = { link = 'DiagnosticError' },
  DiagnosticVirtualTextError = { link = 'DiagnosticError' },
  WhichKeyIconRed = { link = 'DiagnosticError' },
  ['@comment.error'] = { link = 'DiagnosticError' },
  DiagnosticHint = { fg = '#B1E8F6' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualLinesHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
  WhichKeyIconCyan = { link = 'DiagnosticHint' },
  DiagnosticInfo = { fg = '#B1F6E1' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualLinesInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
  WhichKeyIconBlue = { link = 'DiagnosticInfo' },
  ['@comment.note'] = { link = 'DiagnosticInfo' },
  DiagnosticOk = { fg = '#B1F6BF' },
  DiagnosticFloatingOk = { link = 'DiagnosticOk' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },
  DiagnosticVirtualLinesOk = { link = 'DiagnosticOk' },
  DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
  WhichKeyIconGreen = { link = 'DiagnosticOk' },
  DiagnosticUnderlineError = { sp = '#FFDD99', underline = true },
  DiagnosticUnderlineHint = { sp = '#B1E8F6', underline = true },
  DiagnosticUnderlineInfo = { sp = '#B1F6E1', underline = true },
  DiagnosticUnderlineOk = { sp = '#B1F6BF', underline = true },
  DiagnosticUnderlineWarn = { sp = '#FFAA99', underline = true },
  DiagnosticWarn = { fg = '#FFDD99' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticVirtualLinesWarn = { link = 'DiagnosticWarn' },
  DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
  WhichKeyIconOrange = { link = 'DiagnosticWarn' },
  WhichKeyIconYellow = { link = 'DiagnosticWarn' },
  ['@comment.warning'] = { link = 'DiagnosticWarn' },
  DiffAdd = { fg = '#B1F6BF', bg = '#151828' },
  GitSignsAddLn = { link = 'DiffAdd' },
  GitSignsAddPreview = { link = 'DiffAdd' },
  TelescopeResultsDiffAdd = { link = 'DiffAdd' },
  DiffChange = { fg = '#FFDD99', bg = '#151828' },
  GitSignsChangeLn = { link = 'DiffChange' },
  TelescopeResultsDiffChange = { link = 'DiffChange' },
  DiffDelete = { fg = '#FF9999', bg = '#151828', bold = true },
  GitSignsDeletePreview = { link = 'DiffDelete' },
  GitSignsDeleteVirtLn = { link = 'DiffDelete' },
  TelescopeResultsDiffDelete = { link = 'DiffDelete' },
  DiffText = { fg = '#B1E8F6', bg = '#151828' },
  Directory = { fg = '#B1F6E1' },
  TelescopePreviewDate = { link = 'Directory' },
  TelescopePreviewDirectory = { link = 'Directory' },
  Error = { fg = 'bg', bg = '#FF6666' },
  NvimInvalid = { link = 'Error' },
  ErrorMsg = { fg = '#FF9999' },
  NvimInvalidSpacing = { link = 'ErrorMsg' },
  FloatShadow = { bg = '#151828', blend = 80 },
  FloatShadowThrough = { bg = '#151828', blend = 100 },
  Folded = { fg = '#C7CBE1', bg = '#151828' },
  Function = { fg = '#BFB1F6' },
  TelescopeResultsClass = { link = 'Function' },
  TelescopeResultsField = { link = 'Function' },
  TelescopeResultsFunction = { link = 'Function' },
  WhichKey = { link = 'Function' },
  WhichKeyIconAzure = { link = 'Function' },
  ['@function'] = { link = 'Function' },
  Identifier = { fg = '#B1E8F6' },
  NvimIdentifier = { link = 'Identifier' },
  TelescopeMultiIcon = { link = 'Identifier' },
  TelescopePromptPrefix = { link = 'Identifier' },
  TelescopeResultsIdentifier = { link = 'Identifier' },
  WhichKeyDesc = { link = 'Identifier' },
  ['@property'] = { link = 'Identifier' },
  LineNr = { fg = '#636FAB' },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  TelescopeResultsLineNr = { link = 'LineNr' },
  MatchParen = { fg = '#FFDD99', bg = '#20253C', bold = true },
  MiniStatuslineModeCommand = { fg = '#FFDD99', bg = '#20253C', bold = true },
  MiniStatuslineModeInsert = { fg = '#B1F6BF', bg = '#20253C', bold = true },
  MiniStatuslineModeNormal = { fg = '#A5ACCF', bg = '#20253C', bold = true },
  MiniStatuslineModeReplace = { fg = '#FF9999', bg = '#20253C', bold = true },
  MiniStatuslineModeVisual = { fg = '#B1F6E1', bg = '#20253C', bold = true },
  ModeMsg = { fg = '#B1F6BF' },
  MoreMsg = { fg = '#B1F6E1' },
  NonText = { fg = '#3B436D' },
  BlinkCmpGhostText = { link = 'NonText' },
  EndOfBuffer = { link = 'NonText' },
  GitSignsCurrentLineBlame = { link = 'NonText' },
  LspCodeLens = { link = 'NonText' },
  LspInlayHint = { link = 'NonText' },
  TelescopePreviewHyphen = { link = 'NonText' },
  TelescopePromptCounter = { link = 'NonText' },
  TelescopeResultsDiffUntracked = { link = 'NonText' },
  Whitespace = { link = 'NonText' },
  NormalFloat = { bg = '#151828' },
  BlinkCmpDoc = { link = 'NormalFloat' },
  BlinkCmpDocBorder = { link = 'NormalFloat' },
  BlinkCmpDocSeparator = { link = 'NormalFloat' },
  BlinkCmpSignatureHelp = { link = 'NormalFloat' },
  BlinkCmpSignatureHelpBorder = { link = 'NormalFloat' },
  FloatBorder = { link = 'NormalFloat' },
  WhichKeyNormal = { link = 'NormalFloat' },
  NvimInternalError = { fg = '#FF6666', bg = '#FF6666' },
  NvimFigureBrace = { link = 'NvimInternalError' },
  NvimInvalidSingleQuotedUnknownEscape = { link = 'NvimInternalError' },
  NvimSingleQuotedUnknownEscape = { link = 'NvimInternalError' },
  Operator = { fg = '#A5ACCF' },
  NvimAssignment = { link = 'Operator' },
  NvimOperator = { link = 'Operator' },
  TelescopeResultsOperator = { link = 'Operator' },
  ['@operator'] = { link = 'Operator' },
  Pmenu = { bg = '#20253C' },
  BlinkCmpMenu = { link = 'Pmenu' },
  BlinkCmpMenuBorder = { link = 'Pmenu' },
  PmenuExtra = { link = 'Pmenu' },
  PmenuKind = { link = 'Pmenu' },
  PmenuSbar = { link = 'Pmenu' },
  PmenuMatch = { bold = true },
  PmenuMatchSel = { bold = true },
  PmenuSel = { blend = 0, reverse = true },
  BlinkCmpMenuSelection = { link = 'PmenuSel' },
  PmenuExtraSel = { link = 'PmenuSel' },
  PmenuKindSel = { link = 'PmenuSel' },
  WildMenu = { link = 'PmenuSel' },
  PmenuThumb = { bg = '#20253C' },
  BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
  PreProc = { fg = '#A5ACCF' },
  Define = { link = 'PreProc' },
  Include = { link = 'PreProc' },
  Macro = { link = 'PreProc' },
  PreCondit = { link = 'PreProc' },
  Question = { fg = '#B1F6E1' },
  QuickFixLine = { fg = '#B1F6E1' },
  RedrawDebugClear = { fg = 'bg', bg = '#FFAA99' },
  RedrawDebugComposed = { fg = 'bg', bg = '#B1F6BF' },
  RedrawDebugNormal = { reverse = true },
  RedrawDebugRecompose = { fg = 'bg', bg = '#FF6666' },
  Removed = { fg = '#FF9999' },
  GitSignsDelete = { link = 'Removed' },
  ['@diff.minus'] = { link = 'Removed' },
  Search = { fg = '#636FAB', bg = '#FFCC66' },
  Substitute = { link = 'Search' },
  TelescopePreviewMatch = { link = 'Search' },
  SignColumn = { fg = '#151828' },
  CursorLineSign = { link = 'SignColumn' },
  FoldColumn = { link = 'SignColumn' },
  Special = { fg = '#B1C6F6' },
  Debug = { link = 'Special' },
  SpecialChar = { link = 'Special' },
  SpecialComment = { link = 'Special' },
  Tag = { link = 'Special' },
  TelescopeMatching = { link = 'Special' },
  TelescopePreviewLink = { link = 'Special' },
  ['@attribute.builtin'] = { link = 'Special' },
  ['@constant.builtin'] = { link = 'Special' },
  ['@constructor'] = { link = 'Special' },
  ['@function.builtin'] = { link = 'Special' },
  ['@markup'] = { link = 'Special' },
  ['@module.builtin'] = { link = 'Special' },
  ['@punctuation.special'] = { link = 'Special' },
  ['@tag.builtin'] = { link = 'Special' },
  ['@type.builtin'] = { link = 'Special' },
  ['@variable.builtin'] = { link = 'Special' },
  ['@variable.parameter.builtin'] = { link = 'Special' },
  SpecialKey = { fg = '#3B436D' },
  SpellBad = { sp = '#FF9999', undercurl = true },
  SpellCap = { sp = '#FFDD99', undercurl = true },
  SpellLocal = { sp = '#B1F6BF', undercurl = true },
  SpellRare = { sp = '#B1F6E1', undercurl = true },
  Statement = { fg = '#B1E8F6', bold = true },
  Conditional = { link = 'Statement' },
  Exception = { link = 'Statement' },
  Keyword = { link = 'Statement' },
  Label = { link = 'Statement' },
  Repeat = { link = 'Statement' },
  TelescopePreviewSocket = { link = 'Statement' },
  TelescopePreviewWrite = { link = 'Statement' },
  StatusLine = { fg = '#151828', bg = '#A5ACCF' },
  MiniStatuslineDevinfo = { link = 'StatusLine' },
  MiniStatuslineFileinfo = { link = 'StatusLine' },
  MsgSeparator = { link = 'StatusLine' },
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineNC = { fg = '#C7CBE1', bg = '#3B436D' },
  MiniStatuslineFilename = { link = 'StatusLineNC' },
  MiniStatuslineInactive = { link = 'StatusLineNC' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  TabLine = { link = 'StatusLineNC' },
  String = { fg = '#B1F6BF' },
  NvimString = { link = 'String' },
  TelescopePreviewExecute = { link = 'String' },
  TelescopePreviewSize = { link = 'String' },
  ['@string'] = { link = 'String' },
  TabLineSel = { bold = true },
  TermCursor = { reverse = true },
  GitSignsAddInline = { link = 'TermCursor' },
  GitSignsChangeInline = { link = 'TermCursor' },
  GitSignsDeleteInline = { link = 'TermCursor' },
  Title = { fg = '#C7CBE1', bold = true },
  FloatTitle = { link = 'Title' },
  ['@markup.heading'] = { link = 'Title' },
  Todo = { fg = '#B1C6F6', bold = true },
  ['@comment.todo'] = { link = 'Todo' },
  TodoBgFIX = { fg = 'bg', bg = '#FF9999', bold = true },
  TodoBgHACK = { fg = 'bg', bg = '#FFDD99', bold = true },
  TodoBgNOTE = { fg = 'bg', bg = '#B1C6F6', bold = true },
  TodoBgPERF = { fg = 'bg', bg = '#F6B1E8', bold = true },
  TodoBgTEST = { fg = 'bg', bg = '#BFB1F6', bold = true },
  TodoBgTODO = { fg = 'bg', bg = '#B1F6BF', bold = true },
  TodoBgWARN = { fg = 'bg', bg = '#FFAA99', bold = true },
  TodoFgFIX = { fg = '#FF9999' },
  TodoFgHACK = { fg = '#FFDD99' },
  TodoFgNOTE = { fg = '#B1C6F6' },
  TodoFgPERF = { fg = '#F6B1E8' },
  TodoFgTEST = { fg = '#BFB1F6' },
  TodoFgTODO = { fg = '#B1F6BF' },
  TodoFgWARN = { fg = '#FFAA99' },
  TodoSignFIX = { fg = '#FF9999' },
  TodoSignHACK = { fg = '#FFDD99' },
  TodoSignNOTE = { fg = '#B1C6F6' },
  TodoSignPERF = { fg = '#F6B1E8' },
  TodoSignTEST = { fg = '#BFB1F6' },
  TodoSignTODO = { fg = '#B1F6BF' },
  TodoSignWARN = { fg = '#FFAA99' },
  Type = { fg = '#E8EAF3' },
  NvimNumberPrefix = { link = 'Type' },
  NvimOptionSigil = { link = 'Type' },
  StorageClass = { link = 'Type' },
  Structure = { link = 'Type' },
  TelescopeMultiSelection = { link = 'Type' },
  Typedef = { link = 'Type' },
  ['@type'] = { link = 'Type' },
  Underlined = { underline = true },
  Visual = { bg = '#3B436D' },
  BlinkCmpDocCursorLine = { link = 'Visual' },
  LspReferenceText = { link = 'Visual' },
  LspSignatureActiveParameter = { link = 'Visual' },
  SnippetTabstop = { link = 'Visual' },
  TelescopePreviewLine = { link = 'Visual' },
  TelescopeSelection = { link = 'Visual' },
  VisualNOS = { link = 'Visual' },
  WarningMsg = { fg = '#FFDD99' },
  WinBar = { fg = '#C7CBE1', bg = '#151828', bold = true },
  WinBarNC = { fg = '#C7CBE1', bg = '#151828' },
  lCursor = { fg = 'bg', bg = 'fg' },
  ['@markup.heading.1.delimiter.vimdoc'] = { fg = 'bg', bg = 'bg', sp = 'fg', nocombine = true, underdouble = true },
  ['@markup.heading.2.delimiter.vimdoc'] = { fg = 'bg', bg = 'bg', sp = 'fg', nocombine = true, underline = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.strong'] = { bold = true },
  ['@markup.underline'] = { underline = true },
  ['@string.special.url'] = { italic = true, underline = true },
  ['@markup.link'] = { link = '@string.special.url' },
  ['@variable'] = { fg = '#E8EAF3' },
  ['@lsp.type.variable'] = { link = '@variable' },
}

-- colorschemes generally want to do this
vim.cmd 'highlight clear'
vim.cmd 'set t_Co=256'
vim.cmd "let g:colors_name='requiemDark'"

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
